[workspace]
resolver = "3"
members = [
    "svudko-common",
    "svudko-core",
    "svudko-desktop",
    "svudko-resolvers/*",
]

[workspace.package]
license = "MIT"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
thiserror = "2.0"

tracing = { version = "0.1", features = [] }
tracing-subscriber = { version = "0.3", features = [] }

# networking
quinn = "0.11"
mdns-sd = "0.20"

# crypto
rcgen = "0.14"
x509-parser = "0.18"

# crux family
crux_core = "0.19"
# facet = "=0.44"
boltffi = { version = "0.26" }

# types
uuid = { version = "1.23", features = ["v4"] }

# tools
data-encoding = "2.11"
gethostname = "1"
sha2 = "0.11"
dirs = "6"
# rkyv = "0.8"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

# other
sqlx = { version = "0.9", default-features = false }
tokio = { version = "1.52" }

# ui tools
slint = { version = "1.15", default-features = false }
rfd = "0.17"
# even through I use tokio, but slint uses smol, so instead of mixing desktop uses 
# smol runtime outside of core
smol = "2.0"

# local
svudko-common = { path = "./svudko-common" }
svudko-core = { path = "./svudko-core" }
# local resolvers for core
svudko-resolver-exchange = { path = "./svudko-resolvers/svudko-resolver-exchange" }
svudko-resolver-sd = { path = "./svudko-resolvers/svudko-resolver-sd" }
svudko-resolver-storage = { path = "./svudko-resolvers/svudko-resolver-storage" }

[workspace.lints.rust]
rust_2018_idioms = "deny"
# missing_docs = "deny"
missing_debug_implementations = "allow"
future_incompatible = "deny"
unsafe-code = "deny"

[workspace.lints.clippy]
unused_async = "deny"
pedantic = "warn"
