[package]
name = "svudko-resolver-exchange"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
rcgen = { workspace = true, features = ["pem", "x509-parser"]}  
x509-parser.workspace = true
svudko-common.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
quinn.workspace = true 
data-encoding.workspace = true 
sha2.workspace = true
rkyv.workspace = true
dirs.workspace = true

