import { ComponentPosition } from "../components/mod.slint";
import { IconBtn } from "../components/icon_button.slint";
import { Theme } from "../theme.slint";
import { Logic, TabIndex } from "../logic.slint";
import { Icons } from "../icons.slint";
import { Divider } from "../components/divider.slint";
import { Util } from "../components/utils.slint";

export component VerticalStatusBar inherits Rectangle {
    height: 100%;
    width: Theme.sidebar-width;
    background: Theme.secondary-background;
    // border-radius: Theme.border-radius;

    private property <bool> is-show-tip: true;
    private property <bool> show-icon-hover-background: false;
    private property <length> icon-size: Theme.icon-size;
    private property <ComponentPosition> tip-position: ComponentPosition.Right;
    in-out property <length> v-padding-bottom;
    in-out property v-padding <=> vbox.padding;
    in-out property v-spacing <=> vbox.spacing;

    VerticalLayout {
        alignment: space-between;

        VerticalLayout {
            spacing: Theme.spacing * 5;
            padding: Theme.padding * 2;
            padding-top: Theme.padding * 2;

            IconBtn {
                icon: Icons.home;
                icon-size: root.icon-size;
                show-icon-hover-background: root.show-icon-hover-background;
                colorize: Logic.current-tab-index == TabIndex.Home ? Theme.thirdly-brand-color : Theme.icon-color;
                is-show-tip: root.is-show-tip;
                tip-position: root.tip-position;
                tip: "Home";

                clicked => {
                    Logic.switch-tab(TabIndex.Home);
                }
            }
        }

        vbox := VerticalLayout {
            padding: Theme.padding * 2;
            padding-bottom: root.v-padding-bottom;

            VerticalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    alignment: center;

                    Divider {
                        width: Theme.default-font-size;
                        height: 2px;
                    }
                }
            }

            VerticalLayout {
                spacing: Theme.spacing * 4;
                padding-top: Theme.padding * 2;
                padding-bottom: Theme.padding * 2;

                IconBtn {
                    icon: Icons.settings;
                    icon-size: root.icon-size;
                    show-icon-hover-background: root.show-icon-hover-background;
                    is-show-tip: root.is-show-tip;
                    tip-position: root.tip-position;
                    tip: "Pairing";

                    clicked => {
                        Logic.switch-tab(TabIndex.Pairing);
                    }
                }

                IconBtn {
                    icon: Icons.settings;
                    icon-size: root.icon-size;
                    show-icon-hover-background: root.show-icon-hover-background;
                    is-show-tip: root.is-show-tip;
                    tip-position: root.tip-position;
                    tip: "Settings";

                    clicked => {
                         Logic.switch-tab(TabIndex.Settings);
                    }
                }

                IconBtn {
                    icon: Icons.github;
                    icon-size: root.icon-size;
                    show-icon-hover-background: root.show-icon-hover-background;
                    is-show-tip: root.is-show-tip;
                    tip-position: root.tip-position;
                    tip: "Github";

                    clicked => {
                        Util.open-url("Default", "https://github.com/NYBACHOK/svudko");
                    }
                }
            }
        }
    }
}
