import { ComponentPosition } from "../components/mod.slint";
import { IconBtn } from "../components/icon_button.slint";
import { Theme } from "../theme.slint";
import { VerticalSettingIconsBar } from "vertical_settings_icons_bar.slint";
import { Logic, TabIndex } from "../logic.slint";
import { Icons } from "../icons.slint";

export component VerticalStatusBar inherits Rectangle {
    width: Theme.sidebar-width;
    background: Theme.secondary-background;

    private property <bool> is-show-tip: true;
    private property <bool> show-icon-hover-background: false;
    private property <length> icon-size: Theme.icon-size;
    private property <ComponentPosition> tip-position: ComponentPosition.Right;

    VerticalLayout {
        alignment: space-between;

        VerticalLayout {
            spacing: Theme.spacing * 5;
            padding: Theme.padding * 2;
            padding-top: Theme.padding * 3;

            IconBtn {
                icon: Icons.home;
                icon-size: root.icon-size;
                show-icon-hover-background: root.show-icon-hover-background;
                colorize: Logic.current-tab-index == TabIndex.Home ? Theme.thirdly-brand-color : Theme.icon-color;
                is-show-tip: root.is-show-tip;
                tip-position: root.tip-position;
                tip: "Home";

                clicked => {
                    Logic.switch-tab(TabIndex.Home);
                }
            }
        }

        VerticalSettingIconsBar {
            icon-size: Theme.icon-size;
            v-spacing: Theme.spacing * 5;
            v-padding: Theme.padding * 2;
            v-padding-bottom: Theme.padding * 5;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
        }
    }
}