[package]
name = "svudko-cli"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4.6", features = ["derive"]}
anyhow.workspace = true
tracing.workspace = true
quinn = "0.11"
tokio = {workspace = true, features = ["full"]}
rcgen = "0.14"
dirs = "6"