[package]
name = "svudko-cli"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"]}

svudko-common = { path = "../svudko-common"}
svudko-core = { path = "../svudko-core"}

 
tokio = {workspace = true, features = ["full"]}
rcgen = "0.14"
