[package]
name = "svudko-desktop"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
slint = { version = "1.15", default-features = false, features = [
    "std",
    "compat-1-2",
    "backend-winit",
    "renderer-femtovg",
    "renderer-software",
    "log",
] }
svudko-core.workspace = true
smol = { workspace = true }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
svudko-resolver-sd.workspace = true

[build-dependencies]
slint-build = "1.15"
