import {
    ListView,
    HorizontalBox,
    Button,
} from "std-widgets.slint";
import { Logic, LocalDevices, Hostname } from "../logic.slint";
import { Theme } from "../theme.slint";
import { NoDataImg } from "../components/no_data.slint";
import { CenterLayout } from "../components/center_layout.slint";
import { IconBtn } from "../components/icon_button.slint";
import { Icons } from "../icons.slint";
import { Divider } from "../components/divider.slint";

export component Pairing inherits Rectangle {
    in-out property <[Hostname]> pairing_requests <=> Logic.model.pairing_requests;

    background: Theme.secondary-background;

    padding: Theme.padding;

    if pairing_requests.length == 0: NoDataImg {
        text: "No pending requests";
    }

    ListView {
        for request[i] in pairing_requests: CenterLayout {
            HorizontalLayout {
                padding: Theme.padding;
                Text {

                    text: request.name;
                    vertical-alignment: center;
                    color: Theme.primary-text-color;
                }

                IconBtn {
                    text: "Accept";
                    text-color: Theme.secondary-text-color;

                    icon: Icons.placeholder;
                    border-color: Theme.dark-text-color;
                    border-radius: Theme.border-radius;

                    bg-color: Theme.thirdly-brand-color;

                    clicked => {
                        Logic.pair_response(request, true)
                    }
                }

                IconBtn {
                    text: "Deny";
                    text-color: Theme.secondary-text-color;

                    icon: Icons.placeholder;
                    border-color: Theme.dark-text-color;
                    border-radius: Theme.border-radius;

                    bg-color: Theme.thirdly-brand-color;

                    clicked => {
                        Logic.pair_response(request, false)
                    }
                }
            }
        }
    }
}
