[package]
name = "svudko-core"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "codegen"
required-features = ["codegen"]

[dependencies]
tracing.workspace = true
thiserror.workspace = true
# serde.workspace = true
tokio = { workspace = true, features = ["full"] }
dirs = "6"
anyhow.workspace = true
mdns-sd.workspace = true

crux_core.workspace = true

# local
svudko-common.workspace = true
svudko-resolver-sd.workspace = true
svudko-resolver-exchange.workspace = true
svudko-resolver-storage.workspace = true

# optional dependencies
boltffi = { workspace = true, optional = true }
clap = { workspace = true, optional = true, features = ["derive"] }
log = { version = "0.4", optional = true }
pretty_env_logger = { version = "0.5", optional = true }

[features]
default = []
ffi = ["dep:boltffi"]
codegen = [
    "dep:clap",
    "dep:log",
    "dep:pretty_env_logger",
    "crux_core/facet_typegen",
]
