import {
    Button,
    VerticalBox,
    HorizontalBox,
    ListView,
} from "std-widgets.slint";

struct ViewModel {
    enabled_discover: bool,
    discovered_hosts: [string],
}

export component AppWindow inherits Window {
    in-out property <ViewModel> model;
    in-out property <string> error_msg: "";

    callback enable_discover();
    callback disable_discover();

    callback start_scan();
    callback connect_to_host(string);
    callback send_debug_file(string);

    min-width: 360px;
    min-height: 500px;
    title: "Svudko";
    background: #17171a;

    VerticalLayout {
        ListView {
            for host[i] in model.discovered-hosts: HorizontalBox {

                HorizontalBox {
                    height: 20%;
                    Text {
                        text: host;
                        vertical-alignment: center;
                        color: #ffffff;
                    }

                    Button {
                        text: "Connect";
                        clicked => {
                            root.connect_to_host(host);
                        }
                    }

                    Button {
                        text: "Send Debug File";
                        clicked => {
                            root.send_debug_file(host)
                        }
                    }
                }
            }
        }

        HorizontalBox {
            if (model.enabled-discover): Text {
                text: "Made this PC available in Network";
            }
        }

        HorizontalBox {
            VerticalBox {
                height: 20%;
                Button {
                    text: "Enable Discover";
                    clicked => {
                        enable_discover()
                    }
                }

                Button {
                    text: "Disable Discover";
                    clicked => {
                        disable_discover()
                    }
                }
            }

            VerticalBox {
                height: 20%;
                Button {
                    text: "Scan";
                    clicked => {
                        start_scan()
                    }
                }
            }
        }

        if (error_msg != ""): HorizontalBox {
            Text {
                text: error_msg;
                horizontal-alignment: center;
                vertical-alignment: bottom;
                font-size: 20px;
                color: #d82222;
            }
        }
    }
}
