import { Theme } from "theme.slint";
import { Icons } from "icons.slint";
import { MainPanel } from "panels/main.slint";
import { Home } from "pages/home.slint";

import { ViewModel, Logic } from "./logic.slint";

export component AppWindow inherits Window {
    title: "Svudko";

    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;
    default-font-size: Theme.default-font-size;
    default-font-weight: Theme.normal-font-weight;
    default-font-family: Theme.default-font-family;
    background: Theme.base-background;
    icon: Icons.app;

    HorizontalLayout {
        MainPanel { }

        Home { }
    }
}

export { Logic }
