import { Theme } from "theme.slint";
import { Icons } from "icons.slint";
import { MainPanel } from "panels/main.slint";
import { Send } from "pages/send.slint";
import { Util } from "components/utils.slint";

import { ViewModel, Logic, TabIndex } from "./logic.slint";
import { Pairing } from "pages/pairing.slint";
import { Settings } from "pages/settings.slint";

export component AppWindow inherits Window {
    title: "Svudko";
    icon: Icons.app;

    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;
    default-font-size: Theme.default-font-size;
    default-font-weight: Theme.normal-font-weight;
    default-font-family: Theme.default-font-family;
    background: Theme.base-background;

    HorizontalLayout {
        MainPanel { }

        if  Logic.current-tab-index == TabIndex.Send: Send { }

        if  Logic.current-tab-index == TabIndex.Pairing: Pairing { }

        if  Logic.current-tab-index == TabIndex.Settings: Settings { }
    }
}

export { Logic, Util }
