 
export global Icons {
     in property <image> home:  @image-url("./icons/placeholder.svg");

     in property <image> directory-arrow-left:  @image-url("./icons/directory-arrow-up.svg");
     in property <image> settings:  @image-url("./icons/placeholder.svg");
     in property <image> github:  @image-url("./icons/placeholder.svg");
     
     in property <image> app:  @image-url("./icons/placeholder.svg");

     in property <image> no_data:  @image-url("./icons/placeholder.svg");
     in property <image> send_files:  @image-url("./icons/placeholder.svg");
}