export global Icons {
     // Pages
     in property <image> send:  @image-url("./icons/send-black.svg");
     in property <image> pairing:  @image-url("./icons/pairing-black.svg");
     in property <image> settings:  @image-url("./icons/gear-black.svg");
     in property <image> github:  @image-url("./icons/github-black.svg");

     // Items
     in property <image> directory-arrow-left:  @image-url("./icons/directory-arrow-up-black.svg");
     in property <image> wifi:  @image-url("./icons/wifi-black.svg");
     in property <image> pairing_item:  @image-url("./icons/pairing-black-item.svg");

     // Special
     in property <image> app:  @image-url("./icons/placeholder.svg");
     in property <image> no_data:  @image-url("./icons/placeholder.svg");
     in property <image> placeholder:  @image-url("./icons/placeholder.svg");
}
