export enum TabIndex {
    Send,
    Pairing,
    Settings,
}

export enum PopupIndex {
    None,
    Setting,
}

export struct Hostname {
    name: string,
}

export struct LocalDevices {
    hostname: Hostname,
    paired: bool,
}

export struct ViewModel {
    discovered_hosts: [LocalDevices],
    pairing_requests: [Hostname],
}

export global Logic {
    in-out property <TabIndex> current-tab-index: TabIndex.Send;
    in-out property <ViewModel> model;
    in-out property <string> error_msg: "";

    callback select_and_send_files(Hostname);
    callback pair_request(Hostname);
    callback pair_response(Hostname, bool);

    public function switch-tab(index: TabIndex) {
        if (Logic.current-tab-index != index) {
            Logic.current-tab-index = index;
        }
    }
}
