export enum TabIndex {
    Home,
}

export enum PopupIndex {
    None,
    Setting,
}

export struct Hostname {
    name: string,
}

export struct LocalDevices {
    hostname: Hostname,
    paired: bool,
}

export struct ViewModel {
    discovered_hosts: [LocalDevices],
}

export global Logic {
    in-out property <TabIndex> current-tab-index: TabIndex.Home;
    in-out property <ViewModel> model;
    in-out property <string> error_msg: "";

    callback open_settings();
    callback select_files(Hostname);
    callback pair_devices(Hostname);

    public function switch-tab(index: TabIndex) {
        if (Logic.current-tab-index != index) {
            Logic.current-tab-index = index;
        }
    }
}
